apiVersion: aws.platform.upbound.io/v1alpha1
kind: XNetwork
metadata:
  name: ref-aws-network
spec:
  parameters:
    id: platform-ref-aws
    region: us-west-2
status:
  subnetIds:
    - subnet-abc
    - subnet-def
    - subnet-ghi
    - subnet-jkl
  securityGroupIds:
    - sg-abc
